# 基础镜像
FROM alpine:latest

# 作者信息
LABEL maintainer="𝑬𝓷𝒅𝒆 ℵ" \
      version="1.9.2"

# 工作目录
WORKDIR /root

# 设置时区
ENV TZ=Asia/Shanghai

# 复制文件
COPY shellcrash.sh /root/shellcrash.sh
# 设置脚本的可执行权限并安装必要软件
RUN set -ex \
    && chmod +x /root/shellcrash.sh \
    && apk add --no-cache curl wget nftables tzdata \
    && cp /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo ${TZ} > /etc/timezone && apk del tzdata \
    # 安装ShellCrash
    && wget https://raw.githubusercontent.com/juewuy/ShellCrash/master/install.sh \
    && (echo "1"; sleep 1; echo "1"; sleep 3; echo "1"; sleep 1; echo "1"; sleep 5) | sh install.sh \
    # 配置ShellCrash
    && source /etc/profile &> /dev/null \
    # && (echo "2"; sleep 2; echo "0"; sleep 2; echo "1"; sleep 2; echo "1"; sleep 2; echo "2"; sleep 2; echo "1"; sleep 2; \
    # && echo "https://suo.yt/4oz7ctI"; sleep 2; echo "1"; sleep 5; echo "1"; sleep 5; echo "0") | /etc/ShellCrash/menu.sh \
    && (echo "2"; sleep 2; \
        echo "1"; sleep 4; \
        echo "1"; sleep 2; \
        echo "2"; sleep 2; \
        echo "1"; sleep 2; \
        echo "https://github.com/NasPilot/shellcrash/raw/main/config.yaml"; sleep 4; \
        echo "1"; sleep 4; \
        #echo "1"; sleep 2; \
        #echo "0"; sleep 2; \
        #echo "1"; sleep 2; \
        echo "0") | /etc/ShellCrash/menu.sh \
    && mv /etc/ShellCrash /etc/ShellCrash_bak && mkdir /etc/ShellCrash \
    && rm -rf /tmp/* /var/cache/apk/*

# 端口映射
EXPOSE 7890 9999

# 设置环境变量
ENV ENV="/etc/profile"

# 启动命令
ENTRYPOINT ["sh","shellcrash.sh"]