#!/command/with-contenv sh

# 检查 /etc/ShellCrash 目录是否为空
# 如果目录下的文件数量等于 0，则认为是首次运行
if [ ! -f "/etc/ShellCrash/config.yaml" ]; then
  echo ">>> First run detected. Initializing /etc/ShellCrash from backup..."
  # 从备份目录复制所有文件和子目录到 /etc/ShellCrash
  # -a 标志可以保留文件属性、递归复制等
  cp -a /etc/ShellCrash.bak/. /etc/ShellCrash/
  echo ">>> Initialization complete."
else
  echo ">>> Existing configuration found in /etc/ShellCrash. Skipping initialization."
fi
